# This file was generated by GoReleaser. DO NOT EDIT.
cask "mediainfo" do
  binary "mediainfo", target: "go-mediainfo"
  caveats <<~EOS
    If you already have Homebrew's MediaInfo installed, the `mediainfo` symlink may already exist.
    Use `go-mediainfo` to run this cask's binary.
  EOS

  name "mediainfo"
  desc "Go rewrite of MediaInfo CLI."
  homepage "https://github.com/autobrr/go-mediainfo"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mediainfo"

  on_macos do
    on_intel do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_darwin_amd64.tar.gz"
      sha256 "11f0ed4fbeb7c555b731dcb6ee9a2ba0b3f95693e3422cf0d291e971f79331af"
    end
    on_arm do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_darwin_arm64.tar.gz"
      sha256 "02cb6bbe67e4f30e8d96e075ea6d7764091bc49d454c81b4afd29775e465b7a5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_linux_amd64.tar.gz"
      sha256 "4c77d9100699f0f5bc2cb365fddc012a840c788c459b3928218de327ee29ac32"
    end
    on_arm do
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_linux_arm64.tar.gz"
      sha256 "7426a03e4d5f0362740a035b6d2cb34fe418ef4561d1b77faea9d2534cef4673"
    end
  end

  # No zap stanza required
end
