# This file was generated by GoReleaser. DO NOT EDIT.
cask "mediainfo" do
  binary "mediainfo", target: "go-mediainfo"
  caveats <<~EOS
    If you already have Homebrew's MediaInfo installed, the `mediainfo` symlink may already exist.
    Use `go-mediainfo` to run this cask's binary.
  EOS

  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "49fd0ba7fb43300fece73d26413741cb4bf69ea8d761c869603b237c6943b8a4"
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "03d2a91235d6e5a636aa57da6ae7dfc9d285018e299f4ae684d0b8c0d544d293"
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a40d1d716fc605b68a3ed0729067fd4b5773e23e4cb69d19939296ceda6dca10"
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "28d034212081f75532aaff17b2c060968de706073ec306b298b69c594da67c60"
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mediainfo"
  desc "Go rewrite of MediaInfo CLI."
  homepage "https://github.com/autobrr/go-mediainfo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mediainfo"

  # No zap stanza required

end
