# This file was generated by GoReleaser. DO NOT EDIT.
cask "mediainfo" do
  binary "mediainfo", target: "go-mediainfo"
  caveats <<~EOS
    If you already have Homebrew's MediaInfo installed, the `mediainfo` symlink may already exist.
    Use `go-mediainfo` to run this cask's binary.
  EOS

  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "f44daa6170671a55759373300490f612de6ee001ba92636314420df013f37681"
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1232620ce8585847501dabe03621ca69521a7d54b6c3e308e56b64ac6178052b"
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ba6772ab8a3b69cd79d7a13da7933cffab3775d5ca0513918fef8da1a013decc"
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c1f1e7bbdf7fd24cd1ad784d246fe05ee819994651b082455bd4099af7df1a90"
      url "https://github.com/autobrr/go-mediainfo/releases/download/v#{version}/mediainfo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mediainfo"
  desc "Go rewrite of MediaInfo CLI."
  homepage "https://github.com/autobrr/go-mediainfo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mediainfo"

  # No zap stanza required

end
