package mediainfo

var generalFieldOrder = map[string]int{
	"Complete name":         0,
	"Format":                1,
	"Format profile":        2,
	"Format version":        3,
	"Codec ID":              4,
	"Unique ID":             5,
	"File size":             6,
	"Duration":              7,
	"Overall bit rate mode": 8,
	"Overall bit rate":      9,
	"Frame rate":            10,
	"Writing application":   11,
	"Writing library":       12,
}

var streamFieldOrder = map[string]int{
	"ID":                                0,
	"Format":                            1,
	"Format/Info":                       2,
	"Format profile":                    3,
	"Format settings":                   4,
	"Format settings, CABAC":            5,
	"Format settings, Reference frames": 6,
	"Codec ID":                          7,
	"Codec ID/Info":                     8,
	"Duration":                          9,
	"Source duration":                   10,
	"Source_Duration_LastFrame":         11,
	"Bit rate mode":                     12,
	"Bit rate":                          13,
	"Nominal bit rate":                  14,
	"Maximum bit rate":                  15,
	"Width":                             16,
	"Height":                            17,
	"Display aspect ratio":              18,
	"Channel(s)":                        19,
	"Channel layout":                    20,
	"Sampling rate":                     21,
	"Frame rate mode":                   22,
	"Frame rate":                        23,
	"Chroma subsampling":                24,
	"Bit depth":                         25,
	"Scan type":                         26,
	"Bits/(Pixel*Frame)":                27,
	"Compression mode":                  28,
	"Stream size":                       29,
	"Source stream size":                30,
	"Writing library":                   31,
	"Encoding settings":                 32,
	"Default":                           33,
	"Alternate group":                   34,
	"Codec configuration box":           35,
}
