package mediainfo

var generalFieldOrder = map[string]int{
	"ID":                    -2,
	"Unique ID":             -1,
	"Complete name":         0,
	"Format":                1,
	"Format profile":        2,
	"Format version":        3,
	"Codec ID":              4,
	"File size":             5,
	"Duration":              6,
	"Overall bit rate mode": 7,
	"Overall bit rate":      8,
	"Frame rate":            9,
	"Writing application":   10,
	"Writing library":       11,
	"ErrorDetectionType":    12,
}

var streamFieldOrder = map[string]int{
	"ID":                                0,
	"Menu ID":                           1,
	"Format":                            2,
	"Format/Info":                       3,
	"Format version":                    4,
	"Muxing mode":                       5,
	"Format profile":                    6,
	"Format settings":                   7,
	"Format settings, CABAC":            8,
	"Format settings, Reference frames": 9,
	"Codec ID":                          10,
	"Codec ID/Info":                     11,
	"Duration":                          12,
	"Source duration":                   13,
	"Source_Duration_LastFrame":         14,
	"Bit rate mode":                     15,
	"Bit rate":                          16,
	"Nominal bit rate":                  17,
	"Maximum bit rate":                  18,
	"Width":                             19,
	"Height":                            20,
	"Display aspect ratio":              21,
	"Channel(s)":                        22,
	"Channel layout":                    23,
	"Sampling rate":                     24,
	"Frame rate mode":                   25,
	"Frame rate":                        26,
	"Chroma subsampling":                27,
	"Bit depth":                         28,
	"Scan type":                         29,
	"Bits/(Pixel*Frame)":                30,
	"Compression mode":                  31,
	"Delay relative to video":           32,
	"Stream size":                       33,
	"Source stream size":                34,
	"Writing library":                   35,
	"Encoding settings":                 36,
	"Default":                           37,
	"Forced":                            38,
	"Color range":                       39,
	"Alternate group":                   40,
	"Codec configuration box":           41,
	"List":                              42,
	"Service name":                      43,
	"Service provider":                  44,
	"Service type":                      45,
}
