package mediainfo

var generalFieldOrder = map[string]int{
	"Complete name":         0,
	"Format":                1,
	"Format profile":        2,
	"Format version":        3,
	"Codec ID":              4,
	"Unique ID":             5,
	"File size":             6,
	"Duration":              7,
	"Overall bit rate mode": 8,
	"Overall bit rate":      9,
	"Frame rate":            10,
	"Writing application":   11,
	"Writing library":       12,
}

var streamFieldOrder = map[string]int{
	"ID":                                0,
	"Format":                            1,
	"Format profile":                    2,
	"Format settings":                   3,
	"Format settings, CABAC":            4,
	"Format settings, Reference frames": 5,
	"Format/Info":                       6,
	"Codec ID":                          7,
	"Duration":                          8,
	"Bit rate mode":                     9,
	"Bit rate":                          10,
	"Nominal bit rate":                  11,
	"Maximum bit rate":                  12,
	"Width":                             13,
	"Height":                            14,
	"Display aspect ratio":              15,
	"Frame rate mode":                   16,
	"Frame rate":                        17,
	"Chroma subsampling":                18,
	"Bit depth":                         19,
	"Scan type":                         20,
	"Channel(s)":                        21,
	"Channel layout":                    22,
	"Sampling rate":                     23,
}
