package mediainfo

import "testing"

func TestNormalizeLanguageCode(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		// 2-letter codes pass through unchanged
		{"en", "en"},
		{"fr", "fr"},
		{"de", "de"},
		{"es", "es"},
		{"ar", "ar"},
		{"bg", "bg"},
		{"bn", "bn"},
		{"ca", "ca"},
		{"cs", "cs"},
		{"da", "da"},
		{"el", "el"},
		{"et", "et"},
		{"fa", "fa"},
		{"fi", "fi"},
		{"gu", "gu"},
		{"he", "he"},
		{"hi", "hi"},
		{"hr", "hr"},
		{"hu", "hu"},
		{"hy", "hy"},
		{"id", "id"},
		{"is", "is"},
		{"it", "it"},
		{"ja", "ja"},
		{"jv", "jv"},
		{"ko", "ko"},
		{"lt", "lt"},
		{"lv", "lv"},
		{"mk", "mk"},
		{"mr", "mr"},
		{"ms", "ms"},
		{"nl", "nl"},
		{"no", "no"},
		{"pa", "pa"},
		{"pl", "pl"},
		{"pt", "pt"},
		{"ro", "ro"},
		{"ru", "ru"},
		{"sk", "sk"},
		{"sl", "sl"},
		{"sr", "sr"},
		{"sv", "sv"},
		{"sw", "sw"},
		{"ta", "ta"},
		{"te", "te"},
		{"th", "th"},
		{"tr", "tr"},
		{"uk", "uk"},
		{"ur", "ur"},
		{"vi", "vi"},
		{"zh", "zh"},
		// 3-letter ISO-639-2 codes → 2-letter
		{"eng", "en"},
		{"fra", "fr"},
		{"fre", "fr"},
		{"deu", "de"},
		{"ger", "de"},
		{"spa", "es"},
		{"ara", "ar"},
		{"bul", "bg"},
		{"ben", "bn"},
		{"cat", "ca"},
		{"ces", "cs"},
		{"cze", "cs"},
		{"dan", "da"},
		{"ell", "el"},
		{"gre", "el"},
		{"est", "et"},
		{"fas", "fa"},
		{"per", "fa"},
		{"fin", "fi"},
		{"guj", "gu"},
		{"heb", "he"},
		{"hin", "hi"},
		{"hrv", "hr"},
		{"hun", "hu"},
		{"hye", "hy"},
		{"arm", "hy"},
		{"ind", "id"},
		{"isl", "is"},
		{"ice", "is"},
		{"ita", "it"},
		{"jpn", "ja"},
		{"jav", "jv"},
		{"kor", "ko"},
		{"lit", "lt"},
		{"lav", "lv"},
		{"mkd", "mk"},
		{"mac", "mk"},
		{"mar", "mr"},
		{"msa", "ms"},
		{"may", "ms"},
		{"nld", "nl"},
		{"dut", "nl"},
		{"nor", "no"},
		{"pan", "pa"},
		{"pol", "pl"},
		{"por", "pt"},
		{"ron", "ro"},
		{"rum", "ro"},
		{"rus", "ru"},
		{"slk", "sk"},
		{"slo", "sk"},
		{"slv", "sl"},
		{"srp", "sr"},
		{"swe", "sv"},
		{"swa", "sw"},
		{"tam", "ta"},
		{"tel", "te"},
		{"tha", "th"},
		{"tur", "tr"},
		{"ukr", "uk"},
		{"urd", "ur"},
		{"vie", "vi"},
		{"zho", "zh"},
		{"chi", "zh"},
		// Subtag casing: region → UPPER, script → TitleCase
		{"en_US", "en-US"},
		{"zh_hans", "zh-Hans"},
		{"zh_hant", "zh-Hant"},
		{"es_419", "es-419"},
		{"fil_PH", "fil-PH"},
		{"pt_BR", "pt-BR"},
		{"pt_PT", "pt-PT"},
		{"fr_CA", "fr-CA"},
		// Undefined → empty
		{"und", ""},
		// Empty / whitespace → empty
		{"", ""},
		{"  ", ""},
	}

	for _, tc := range tests {
		t.Run(tc.input, func(t *testing.T) {
			if got := normalizeLanguageCode(tc.input); got != tc.want {
				t.Errorf("normalizeLanguageCode(%q) = %q, want %q", tc.input, got, tc.want)
			}
		})
	}
}

func TestFormatLanguage(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"en", "English"},
		{"fr", "French"},
		{"de", "German"},
		{"es", "Spanish"},
		{"ar", "Arabic"},
		{"bg", "Bulgarian"},
		{"bn", "Bengali"},
		{"ca", "Catalan"},
		{"cs", "Czech"},
		{"da", "Danish"},
		{"el", "Greek"},
		{"et", "Estonian"},
		{"fa", "Persian"},
		{"fi", "Finnish"},
		{"fil", "Filipino"},
		{"gu", "Gujarati"},
		{"he", "Hebrew"},
		{"hi", "Hindi"},
		{"hr", "Croatian"},
		{"hu", "Hungarian"},
		{"hy", "Armenian"},
		{"id", "Indonesian"},
		{"is", "Icelandic"},
		{"it", "Italian"},
		{"ja", "Japanese"},
		{"jv", "Javanese"},
		{"ko", "Korean"},
		{"lt", "Lithuanian"},
		{"lv", "Latvian"},
		{"mk", "Macedonian"},
		{"mr", "Marathi"},
		{"ms", "Malay"},
		{"nb", "Norwegian Bokmål"},
		{"nl", "Dutch"},
		{"no", "Norwegian"},
		{"pa", "Punjabi"},
		{"pl", "Polish"},
		{"pt", "Português"},
		{"ro", "Romanian"},
		{"ru", "Russian"},
		{"sk", "Slovak"},
		{"sl", "Slovenian"},
		{"sr", "Serbian"},
		{"sv", "Swedish"},
		{"sw", "Swahili"},
		{"ta", "Tamil"},
		{"te", "Telugu"},
		{"th", "Thai"},
		{"tr", "Turkish"},
		{"uk", "Ukrainian"},
		{"ur", "Urdu"},
		{"vi", "Vietnamese"},
		{"zh", "Chinese"},
		// Exact region/script variants
		{"es-419", "Spanish (Latin America)"},
		{"fil-PH", "Filipino (PH)"},
		{"pt-BR", "Português (Brazil)"},
		{"pt-PT", "Português (Portugal)"},
		{"fr-CA", "French (Canada)"},
		{"zh-Hans", "Chinese (Simplified)"},
		{"zh-Hant", "Chinese (Traditional)"},
		// 3-letter codes resolved via normalisation
		{"hin", "Hindi"},
		{"eng", "English"},
		{"fra", "French"},
		{"deu", "German"},
		{"spa", "Spanish"},
		{"ara", "Arabic"},
		{"bul", "Bulgarian"},
		{"ben", "Bengali"},
		{"cat", "Catalan"},
		{"ces", "Czech"},
		{"dan", "Danish"},
		{"ell", "Greek"},
		{"est", "Estonian"},
		{"fas", "Persian"},
		{"fin", "Finnish"},
		{"guj", "Gujarati"},
		{"heb", "Hebrew"},
		{"hrv", "Croatian"},
		{"hun", "Hungarian"},
		{"hye", "Armenian"},
		{"ind", "Indonesian"},
		{"isl", "Icelandic"},
		{"ita", "Italian"},
		{"jpn", "Japanese"},
		{"jav", "Javanese"},
		{"kor", "Korean"},
		{"lit", "Lithuanian"},
		{"lav", "Latvian"},
		{"mkd", "Macedonian"},
		{"mar", "Marathi"},
		{"msa", "Malay"},
		{"nld", "Dutch"},
		{"nor", "Norwegian"},
		{"pan", "Punjabi"},
		{"pol", "Polish"},
		{"por", "Português"},
		{"ron", "Romanian"},
		{"rus", "Russian"},
		{"slk", "Slovak"},
		{"slv", "Slovenian"},
		{"srp", "Serbian"},
		{"swe", "Swedish"},
		{"swa", "Swahili"},
		{"tam", "Tamil"},
		{"tel", "Telugu"},
		{"tha", "Thai"},
		{"tur", "Turkish"},
		{"ukr", "Ukrainian"},
		{"urd", "Urdu"},
		{"vie", "Vietnamese"},
		{"zho", "Chinese"},
		// Underscore variants
		{"en_US", "English (US)"},
		{"zh_Hans", "Chinese (Simplified)"},
		{"pt_BR", "Português (Brazil)"},
		// Undefined / empty → empty
		{"und", ""},
		{"", ""},
	}

	for _, tc := range tests {
		t.Run(tc.input, func(t *testing.T) {
			if got := formatLanguage(tc.input); got != tc.want {
				t.Errorf("formatLanguage(%q) = %q, want %q", tc.input, got, tc.want)
			}
		})
	}
}

func TestFormatLanguageCommonISO639Codes(t *testing.T) {
	tests := map[string]string{
		"jpn":        "Japanese",
		"kor":        "Korean",
		"nld":        "Dutch",
		"iw":         "Hebrew",
		"uk":         "Ukrainian",
		"vi":         "Vietnamese",
		"fil":        "Filipino",
		"fil-PH":     "Filipino (PH)",
		"zxx":        "Silent",
		"pt-BR":      "Português (Brazil)",
		"zh-Hant":    "Chinese (Traditional)",
		"zh-Hant-TW": "Chinese (Hant-TW)",
		"en-US":      "English (US)",
	}
	for code, want := range tests {
		if got := formatLanguage(code); got != want {
			t.Fatalf("formatLanguage(%q) = %q, want %q", code, got, want)
		}
	}
}
