package mediainfo

// psStream accumulates one MPEG-PS elementary stream's identifiers, timing,
// codec probes, byte counts, and canonical source facts.
type psStream struct {
	id                   byte
	subID                byte
	kind                 StreamKind
	format               string
	bytes                uint64
	pts                  ptsTracker
	audioProfile         string
	audioObject          int
	audioMPEGVersion     int
	audioRate            float64
	audioChannels        uint64
	hasAudioInfo         bool
	mpegAudioVersion     byte
	mpegAudioLayer       byte
	mpegAudioBitrateKbps int
	mpegAudioBitrateMin  int
	mpegAudioBitrateMax  int
	mpegAudioChannelMode byte
	audioFrames          uint64
	audioBuffer          []byte
	sampleSection        int
	clockPTS             uint64
	clockHasPTS          bool
	clockAudioStart      uint64
	clockVideoStart      int
	programEndSeen       bool
	ac3Info              ac3Info
	hasAC3               bool
	videoHeaderBytes     uint64
	videoSeqExtBytes     uint64
	videoGOPBytes        uint64
	videoHeaderCarry     []byte
	videoFrameBytes      uint64
	videoFrameBytesCount int
	videoFrameCarry      []byte
	videoFramePos        int64
	videoFrameStart      int64
	videoFrameStartSet   bool
	videoStartZeroRun    int
	videoExtraZeros      uint64
	videoTotalBytes      uint64
	videoLastStartPos    int64
	videoNoPTSPackets    uint64
	videoFields          []Field
	videoAVC             avcConfigInfo
	videoSPS             h264SPSInfo
	hasVideoFields       bool
	videoWidth           uint64
	videoHeight          uint64
	videoFrameRate       float64
	videoSliceCount      int
	videoSliceProbed     bool
	videoIsH264          bool
	videoIsMPEG2         bool
	videoBitRateMode     string
	videoBuffer          []byte
	videoCCCarry         []byte
	videoFrameCount      int
	derivedDuration      float64
	ccFound              bool
	ccOdd                ccTrack
	ccEven               ccTrack
	firstPacketOrder     int
	packetCount          int
}

type ccTrack struct {
	found                    bool
	firstFrame               int
	lastFrame                int
	firstPTS                 uint64
	lastPTS                  uint64
	firstCommandPTS          uint64
	firstCommandFrame        int
	firstDisplayPTS          uint64
	firstDisplayFrame        int
	firstContentPTS          uint64
	lastCommandPTS           uint64
	lastContentPTS           uint64
	currentType              string
	firstType                string
	inBack                   bool
	rollUpLines              int
	currentHasContent        bool
	oldSpecialData1          byte
	oldSpecialData2          byte
	hasOldSpecial            bool
	commandDuplicated        bool
	commandAwaitingDuplicate bool
}
