package cli

import (
	"fmt"
	"io"
)

func Help(program string, stdout io.Writer) {
	fmt.Fprintf(stdout, "Usage: \"%s [-Options...] FileName1 [Filename2...]\"\n", program)
	fmt.Fprintln(stdout, "")
	fmt.Fprintln(stdout, "Options:")
	fmt.Fprintln(stdout, "--Help, -h")
	fmt.Fprintln(stdout, "                    Display this help and exit")
	fmt.Fprintln(stdout, "--Help-Output")
	fmt.Fprintln(stdout, "                    Display help for Output= option")
	fmt.Fprintln(stdout, "--Help-AnOption")
	fmt.Fprintln(stdout, "                    Display help for \"AnOption\"")
	fmt.Fprintln(stdout, "--Version")
	fmt.Fprintln(stdout, "                    Display MediaInfo version and exit")
	fmt.Fprintln(stdout, "")
	fmt.Fprintln(stdout, "--Full, -f")
	fmt.Fprintln(stdout, "                    Full information Display (all internal tags)")
	fmt.Fprintln(stdout, "--Output=HTML")
	fmt.Fprintln(stdout, "                    Full information Display with HTML tags")
	fmt.Fprintln(stdout, "--Output=XML")
	fmt.Fprintln(stdout, "                    Full information Display with XML tags")
	fmt.Fprintln(stdout, "--Output=OLDXML")
	fmt.Fprintln(stdout, "                    Full information Display with XML tags using the older")
	fmt.Fprintln(stdout, "                    MediaInfo schema")
	fmt.Fprintln(stdout, "--Output=JSON")
	fmt.Fprintln(stdout, "                    Full information Display with JSON")
	fmt.Fprintln(stdout, "--Output=CSV")
	fmt.Fprintln(stdout, "                    Full information Display with CSV")
	fmt.Fprintln(stdout, "--Output=EBUCore")
	fmt.Fprintln(stdout, "                    Full information Display with EBUCore compliant XML tags")
	fmt.Fprintln(stdout, "--Output=EBUCore_JSON")
	fmt.Fprintln(stdout, "                    Full information Display with EBUCore 1.8 compliant JSON")
	fmt.Fprintln(stdout, "--Output=PBCore")
	fmt.Fprintln(stdout, "                    Full information Display with PBCore compliant XML tags")
	fmt.Fprintln(stdout, "--Output=PBCore2")
	fmt.Fprintln(stdout, "                    Full information Display with PBCore 2.0 compliant XML tags")
	fmt.Fprintln(stdout, "--Output=Graph_Svg")
	fmt.Fprintln(stdout, "                    Graph Display with SVG")
	fmt.Fprintln(stdout, "--Output=Graph_Dot")
	fmt.Fprintln(stdout, "                    Graph Display with Graphviz DOT")
	fmt.Fprintln(stdout, "--Info_OutputFormats")
	fmt.Fprintln(stdout, "                    Display list of more --Output= parameters")
	fmt.Fprintln(stdout, "--AcquisitionDataOutputMode=segmentParameter")
	fmt.Fprintln(stdout, "                    Display Acquisition Data by segment then parameter (EBUCore")
	fmt.Fprintln(stdout, "                    and NISO Z39.87 outputs)")
	fmt.Fprintln(stdout, "--AcquisitionDataOutputMode=parameterSegment")
	fmt.Fprintln(stdout, "                    Display Acquisition Data by parameter then segment (EBUCore")
	fmt.Fprintln(stdout, "                    and NISO Z39.87 outputs)")
	fmt.Fprintln(stdout, "--ExternalMetadata=...")
	fmt.Fprintln(stdout, "                    Add external metadata to the output (EBUCore output)")
	fmt.Fprintln(stdout, "--ExternalMetadataConfig=...")
	fmt.Fprintln(stdout, "                    Output template for external metadata (EBUCore output)")
	fmt.Fprintln(stdout, "--Info-Parameters")
	fmt.Fprintln(stdout, "                    Display list of Inform= parameters")
	fmt.Fprintln(stdout, "")
	fmt.Fprintln(stdout, "--Language=raw")
	fmt.Fprintln(stdout, "                    Display non-translated unique identifiers (internal text)")
	fmt.Fprintln(stdout, "--LegacyStreamDisplay=1")
	fmt.Fprintln(stdout, "                    Display backward compatibility information for HD/HE audio and 3D/HDR video streams")
	fmt.Fprintln(stdout, "--Cover_Data=base64")
	fmt.Fprintln(stdout, "                    Include cover images as base64 in HTML, XML and JSON output")
	fmt.Fprintln(stdout, "--Trace_Level=1, --Details=1")
	fmt.Fprintln(stdout, "                    Output MediaTrace (https://mediaarea.net/MediaTrace).")
	fmt.Fprintln(stdout, "                    Can be used with --Output=XML to output in MediaTrace XML.")
	fmt.Fprintln(stdout, "--ParseSpeed=...")
	fmt.Fprintln(stdout, "                    Control the balance between parsing speed and the amount of information extracted.")
	fmt.Fprintln(stdout, "                    Value ranges from 0 to 1 where 1 is full parsing and the slowest.")
	fmt.Fprintln(stdout, "                    The default is 0.5.")
	fmt.Fprintln(stdout, "--inform_version=1")
	fmt.Fprintln(stdout, "                    Add MediaInfoLib version to the text output")
	fmt.Fprintln(stdout, "--inform_timestamp=1")
	fmt.Fprintln(stdout, "                    Add report creation timestamp to the text output")
	fmt.Fprintln(stdout, "--File_TestContinuousFileNames=0")
	fmt.Fprintln(stdout, "                    Disable image sequence detection")
	fmt.Fprintln(stdout, "--File_Duplicate=...")
	fmt.Fprintln(stdout, "                    Duplicate streams from a stream having multiple substreams (MPEG-TS only).")
	fmt.Fprintln(stdout, "                    See https://mediaarea.net/en/MediaInfo/Support/SDK/Duplicate for how to use.")
	fmt.Fprintln(stdout, "                    Example: --File_Duplicate=\"file://output_file.ts;program_number=1\" --File_IsSeekable=0")
	fmt.Fprintln(stdout, "--Enable_FFmpeg=1")
	fmt.Fprintln(stdout, "                    Enable FFmpeg plugin")
	fmt.Fprintln(stdout, "--LogFile=...")
	fmt.Fprintln(stdout, "                    Save the output in the specified file")
	fmt.Fprintln(stdout, "--BOM")
	fmt.Fprintln(stdout, "                    Byte order mark for UTF-8 output")
	fmt.Fprintln(stdout, "")
	fmt.Fprintln(stdout, "--Ssl_CertificateFileName=...")
	fmt.Fprintln(stdout, "                    File name of the SSL certificate.")
	fmt.Fprintln(stdout, "                    The default format is \"PEM\" and can be changed")
	fmt.Fprintln(stdout, "                    with --Ssl_CertificateFormat.")
	fmt.Fprintln(stdout, "--Ssl_CertificateFormat=...")
	fmt.Fprintln(stdout, "                    File format of the SSL certificate.")
	fmt.Fprintln(stdout, "                    Supported formats are \"PEM\" and \"DER\"")
	fmt.Fprintln(stdout, "--Ssl_PrivateKeyFileName=...")
	fmt.Fprintln(stdout, "                    File name of the SSL private key.")
	fmt.Fprintln(stdout, "                    The default format is \"PEM\" and can be changed")
	fmt.Fprintln(stdout, "                    with --Ssl_PrivateKeyFormat.")
	fmt.Fprintln(stdout, "                    Note: private key with a password is not supported.")
	fmt.Fprintln(stdout, "--Ssl_PrivateKeyFormat=...")
	fmt.Fprintln(stdout, "                    File format of the SSL private key.")
	fmt.Fprintln(stdout, "                    Supported formats are \"PEM\" and \"DER\"")
	fmt.Fprintln(stdout, "--Ssl_CertificateAuthorityFileName=...")
	fmt.Fprintln(stdout, "                    File name of the SSL certificate authorities")
	fmt.Fprintln(stdout, "                    to verify the peer with.")
	fmt.Fprintln(stdout, "--Ssl_CertificateAuthorityPath=...")
	fmt.Fprintln(stdout, "                    Path of the SSL certificate authorities")
	fmt.Fprintln(stdout, "                    to verify the peer with.")
	fmt.Fprintln(stdout, "--Ssl_CertificateRevocationListFileName=...")
	fmt.Fprintln(stdout, "                    File name of the SSL certificate revocation list.")
	fmt.Fprintln(stdout, "                    The format is \"PEM\"")
	fmt.Fprintln(stdout, "--Ssl_IgnoreSecurity=...")
	fmt.Fprintln(stdout, "                    Does not verify the authenticity of the peer's certificate")
	fmt.Fprintln(stdout, "                    Use it at your own risks")
	fmt.Fprintln(stdout, "--Ssh_PublicKeyFileName=...")
	fmt.Fprintln(stdout, "                    File name of the SSH private key.")
	fmt.Fprintln(stdout, "                    Default is $HOME/.ssh/id_rsa.pub or $HOME/.ssh/id_dsa.pub")
	fmt.Fprintln(stdout, "                    if the HOME environment variable is set, and just")
	fmt.Fprintln(stdout, "                    \"id_rsa.pub\" or \"id_dsa.pub\" in the current directory")
	fmt.Fprintln(stdout, "                    if HOME is not set.")
	fmt.Fprintln(stdout, "                    Note: you need to set both public and private key.")
	fmt.Fprintln(stdout, "--Ssh_PrivateKeyFileName=...")
	fmt.Fprintln(stdout, "                    File name of the SSH private key.")
	fmt.Fprintln(stdout, "                    Default is $HOME/.ssh/id_rsa or $HOME/.ssh/id_dsa")
	fmt.Fprintln(stdout, "                    if the HOME environment variable is set, and just")
	fmt.Fprintln(stdout, "                    \"id_rsa\" or \"id_dsa\" in the current directory")
	fmt.Fprintln(stdout, "                    if HOME is not set.")
	fmt.Fprintln(stdout, "                    Note: you need to set both public and private key.")
	fmt.Fprintln(stdout, "                    Note: private key with a password is not supported.")
	fmt.Fprintln(stdout, "--Ssh_KnownHostsFileName=...")
	fmt.Fprintln(stdout, "                    File name of the known hosts")
	fmt.Fprintln(stdout, "                    The format is the OpenSSH file format (libssh2)")
	fmt.Fprintln(stdout, "                    Default is $HOME/.ssh/known_hosts")
	fmt.Fprintln(stdout, "                    if the HOME environment variable is set, and just")
	fmt.Fprintln(stdout, "                    \"known_hosts\" in the current directory")
	fmt.Fprintln(stdout, "                    if HOME is not set.")
	fmt.Fprintln(stdout, "--Ssh_IgnoreSecurity")
	fmt.Fprintln(stdout, "                    Does not verify the authenticity of the peer")
	fmt.Fprintln(stdout, "                    (you don't need to accept the key with ssh first)")
	fmt.Fprintln(stdout, "                    Use it at your own risks")
}

func HelpNothing(program string, stdout io.Writer) {
	fmt.Fprintf(stdout, "Usage: \"%s [-Options...] FileName1 [Filename2...]\"\n", program)
	fmt.Fprintf(stdout, "\"%s --Help\" for displaying more information\n", program)
}

func HelpOutput(program string, stdout io.Writer) {
	fmt.Fprintln(stdout, "--Output=...  Specify a template (BETA)")
	fmt.Fprintf(stdout, "Usage: \"%s --Output=[xxx;]Text FileName\"\n", program)
	fmt.Fprintln(stdout, "")
	fmt.Fprintln(stdout, "xxx can be: General, Video, Audio, Text, Chapter, Image, Menu")
	fmt.Fprintln(stdout, "Text can be the template text, or a filename")
	fmt.Fprintln(stdout, "     Filename must be in the form file://filename")
	fmt.Fprintln(stdout, "")
	fmt.Fprintln(stdout, "See --Info-Parameters for available parameters in the text")
	fmt.Fprintln(stdout, "(Parameters must be surrounded by \"%\" sign)")
	fmt.Fprintln(stdout, "")
	fmt.Fprintf(stdout, "Usage: \"%s --Output=Video;%%AspectRatio%% FileName\"\n", program)
	fmt.Fprintln(stdout, "")
	fmt.Fprintf(stdout, "Usage: \"%s --Output=Video;file://Video.txt FileName\"\n", program)
	fmt.Fprintln(stdout, "and Video.txt contains ")
	fmt.Fprintln(stdout, "\"%DisplayAspectRatio%\"        for Video Aspect Ratio.")
	fmt.Fprintln(stdout, "")
	fmt.Fprintf(stdout, "Usage: \"%s --Output=file://Text.txt FileName\"\n", program)
	fmt.Fprintln(stdout, "and Text.txt contains")
	fmt.Fprintln(stdout, "\"Video;%DisplayAspectRatio%\"  for Video Aspect Ratio.")
	fmt.Fprintf(stdout, "\"Audio;%%Format%%\"              for Audio Format.\n")
}

func Usage(program string, stdout io.Writer) int {
	HelpNothing(program, stdout)
	return exitError
}
